using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc.Testing;

namespace Learning.Integration.Tests.EndToEnd;

// The OpenAPI document is generated by reflecting over registered endpoints/types; it never touches
// the database, so this factory (unlike LearningApiFactory) skips EnsureDeleted/Migrate entirely.
// That also sidesteps the project's documented E2E gotcha: xUnit runs test classes in parallel, and
// two factories racing EnsureDeleted/Migrate against the same hardcoded LocalDB name fail intermittently
// (each E2E test class needs its own unique DB name/factory - see CLAUDE.md's Database section).
public sealed class OpenApiApiFactory : WebApplicationFactory<Program>
{
    protected override void ConfigureWebHost(IWebHostBuilder builder)
    {
        builder.UseSetting("ConnectionStrings:Engagement",
            @"Server=(localdb)\MSSQLLocalDB;Database=DuolingoEngagement_OpenApi_E2E;Trusted_Connection=True;TrustServerCertificate=True");
        builder.UseSetting("ConnectionStrings:Learning",
            @"Server=(localdb)\MSSQLLocalDB;Database=DuolingoLearning_OpenApi_E2E;Trusted_Connection=True;TrustServerCertificate=True");
        builder.UseSetting("Leagues:Settlement:Enabled", "false");
    }
}
