// <auto-generated />
using System;
using Engagement.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Engagement.Infrastructure.Migrations
{
    [DbContext(typeof(EngagementDbContext))]
    [Migration("20260615173547_AddLeagueWeekSettlement")]
    partial class AddLeagueWeekSettlement
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("engagement")
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Engagement.Domain.LeagueStanding", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("LearnerId");

                    b.Property<DateOnly>("Week")
                        .HasColumnType("date")
                        .HasColumnName("WeekStart");

                    b.Property<string>("Tier")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<int>("WeeklyXp")
                        .HasColumnType("int")
                        .HasColumnName("WeeklyXp");

                    b.HasKey("Id", "Week");

                    b.ToTable("LeagueStandings", "engagement");
                });

            modelBuilder.Entity("Engagement.Domain.LeagueWeekSettlement", b =>
                {
                    b.Property<DateOnly>("Week")
                        .HasColumnType("date")
                        .HasColumnName("WeekStart");

                    b.Property<DateTimeOffset>("SettledAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Week");

                    b.ToTable("LeagueWeekSettlements", "engagement");
                });

            modelBuilder.Entity("Engagement.Domain.LearnerStreak", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("LearnerId");

                    b.Property<int>("CurrentStreak")
                        .HasColumnType("int");

                    b.Property<int>("FreezeBalance")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("LastQualifyingDate")
                        .HasColumnType("date");

                    b.Property<int>("LongestStreak")
                        .HasColumnType("int");

                    b.Property<string>("TimeZone")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("TimeZoneId");

                    b.HasKey("Id");

                    b.ToTable("LearnerStreaks", "engagement");
                });

            modelBuilder.Entity("Engagement.Domain.XpAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("LearnerId");

                    b.Property<int>("TotalXp")
                        .HasColumnType("int")
                        .HasColumnName("TotalXp");

                    b.HasKey("Id");

                    b.ToTable("XpAccounts", "engagement");
                });

            modelBuilder.Entity("Engagement.Domain.XpAccount", b =>
                {
                    b.OwnsMany("Engagement.Domain.AppliedAward", "AppliedAwards", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<int>("Id"));

                            b1.Property<int>("Amount")
                                .HasColumnType("int");

                            b1.Property<DateTimeOffset>("AppliedAt")
                                .HasColumnType("datetimeoffset");

                            b1.Property<Guid>("LearnerId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<Guid>("SourceId")
                                .HasColumnType("uniqueidentifier");

                            b1.HasKey("Id");

                            b1.HasIndex("LearnerId", "SourceId")
                                .IsUnique();

                            b1.ToTable("AppliedAwards", "engagement");

                            b1.WithOwner()
                                .HasForeignKey("LearnerId");
                        });

                    b.Navigation("AppliedAwards");
                });
#pragma warning restore 612, 618
        }
    }
}
