// <auto-generated />
using System;
using Engagement.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Engagement.Infrastructure.Migrations
{
    [DbContext(typeof(EngagementDbContext))]
    [Migration("20260529192409_InitialEngagement")]
    partial class InitialEngagement
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("engagement")
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Engagement.Domain.LearnerEngagement", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("LearnerId");

                    b.Property<int>("TotalXp")
                        .HasColumnType("int")
                        .HasColumnName("TotalXp");

                    b.HasKey("Id");

                    b.ToTable("Learners", "engagement");
                });

            modelBuilder.Entity("Engagement.Domain.LearnerEngagement", b =>
                {
                    b.OwnsMany("Engagement.Domain.AppliedAward", "AppliedAwards", b1 =>
                        {
                            b1.Property<Guid>("LearnerId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<Guid>("SourceId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("Amount")
                                .HasColumnType("int");

                            b1.Property<DateTimeOffset>("AppliedAt")
                                .HasColumnType("datetimeoffset");

                            b1.HasKey("LearnerId", "SourceId");

                            b1.ToTable("AppliedAwards", "engagement");

                            b1.WithOwner()
                                .HasForeignKey("LearnerId");
                        });

                    b.Navigation("AppliedAwards");
                });
#pragma warning restore 612, 618
        }
    }
}
