// <auto-generated />
using System;
using Learning.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Learning.Infrastructure.Migrations
{
    [DbContext(typeof(LearningDbContext))]
    [Migration("20260721204658_AddAttempts")]
    partial class AddAttempts
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("learning")
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Learning.Domain.Attempt", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id");

                    b.Property<Guid>("LearnerId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("LearnerId");

                    b.Property<Guid>("LessonId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("LessonId");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Outcome");

                    b.Property<DateTimeOffset>("SubmittedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("SubmittedAt");

                    b.HasKey("Id");

                    b.ToTable("Attempts", "learning");
                });

            modelBuilder.Entity("Learning.Domain.Course", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id");

                    b.Property<string>("Language")
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)")
                        .HasColumnName("Title");

                    b.HasKey("Id");

                    b.ToTable("Courses", "learning");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            Language = "es",
                            Title = "Spanish"
                        });
                });

            modelBuilder.Entity("Learning.Domain.Lesson", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("bit")
                        .HasColumnName("IsPublished");

                    b.Property<int>("Position")
                        .HasColumnType("int")
                        .HasColumnName("Position");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)")
                        .HasColumnName("Title");

                    b.Property<Guid>("UnitId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("UnitId");

                    b.HasKey("Id");

                    b.ToTable("Lessons", "learning");

                    b.HasData(
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333331"),
                            IsPublished = true,
                            Position = 1,
                            Title = "Greetings",
                            UnitId = new Guid("22222222-2222-2222-2222-222222222221")
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333332"),
                            IsPublished = true,
                            Position = 2,
                            Title = "The verb ser",
                            UnitId = new Guid("22222222-2222-2222-2222-222222222221")
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            IsPublished = true,
                            Position = 1,
                            Title = "At the cafe",
                            UnitId = new Guid("22222222-2222-2222-2222-222222222222")
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333334"),
                            IsPublished = false,
                            Position = 2,
                            Title = "Ordering dessert",
                            UnitId = new Guid("22222222-2222-2222-2222-222222222222")
                        });
                });

            modelBuilder.Entity("Learning.Domain.Unit", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id");

                    b.Property<Guid>("CourseId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("CourseId");

                    b.Property<int>("Position")
                        .HasColumnType("int")
                        .HasColumnName("Position");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)")
                        .HasColumnName("Title");

                    b.HasKey("Id");

                    b.ToTable("Units", "learning");

                    b.HasData(
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222221"),
                            CourseId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Position = 1,
                            Title = "Basics"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            CourseId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Position = 2,
                            Title = "Food"
                        });
                });

            modelBuilder.Entity("Learning.Domain.Attempt", b =>
                {
                    b.OwnsMany("Learning.Domain.Answer", "Answers", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<int>("Id"));

                            b1.Property<Guid>("AttemptId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<Guid>("ExerciseId")
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("ExerciseId");

                            b1.Property<int>("SelectedChoiceIndex")
                                .HasColumnType("int")
                                .HasColumnName("SelectedChoiceIndex");

                            b1.Property<bool>("WasCorrect")
                                .HasColumnType("bit")
                                .HasColumnName("WasCorrect");

                            b1.HasKey("Id");

                            b1.HasIndex("AttemptId");

                            b1.ToTable("Answers", "learning");

                            b1.WithOwner()
                                .HasForeignKey("AttemptId");
                        });

                    b.OwnsOne("Learning.Domain.Score", "Score", b1 =>
                        {
                            b1.Property<Guid>("AttemptId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("Correct")
                                .HasColumnType("int")
                                .HasColumnName("ScoreCorrect");

                            b1.Property<int>("Total")
                                .HasColumnType("int")
                                .HasColumnName("ScoreTotal");

                            b1.HasKey("AttemptId");

                            b1.ToTable("Attempts", "learning");

                            b1.WithOwner()
                                .HasForeignKey("AttemptId");
                        });

                    b.Navigation("Answers");

                    b.Navigation("Score")
                        .IsRequired();
                });

            modelBuilder.Entity("Learning.Domain.Lesson", b =>
                {
                    b.OwnsMany("Learning.Domain.Exercise", "Exercises", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("Id");

                            b1.Property<string>("Choices")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Choices");

                            b1.Property<Guid>("LessonId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("Position")
                                .HasColumnType("int")
                                .HasColumnName("Position");

                            b1.Property<string>("Prompt")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("nvarchar(500)")
                                .HasColumnName("Prompt");

                            b1.Property<int>("_correctChoiceIndex")
                                .HasColumnType("int")
                                .HasColumnName("CorrectChoiceIndex");

                            b1.HasKey("Id");

                            b1.HasIndex("LessonId");

                            b1.ToTable("Exercises", "learning");

                            b1.WithOwner()
                                .HasForeignKey("LessonId");

                            b1.HasData(
                                new
                                {
                                    Id = new Guid("44444444-4444-4444-4444-000000000001"),
                                    Choices = "[\"Hola\",\"Adios\",\"Gracias\"]",
                                    LessonId = new Guid("33333333-3333-3333-3333-333333333331"),
                                    Position = 1,
                                    Prompt = "How do you say hello?",
                                    _correctChoiceIndex = 0
                                },
                                new
                                {
                                    Id = new Guid("44444444-4444-4444-4444-000000000002"),
                                    Choices = "[\"Hola\",\"Adios\",\"Gracias\"]",
                                    LessonId = new Guid("33333333-3333-3333-3333-333333333331"),
                                    Position = 2,
                                    Prompt = "How do you say goodbye?",
                                    _correctChoiceIndex = 1
                                },
                                new
                                {
                                    Id = new Guid("44444444-4444-4444-4444-000000000003"),
                                    Choices = "[\"soy\",\"es\",\"eres\"]",
                                    LessonId = new Guid("33333333-3333-3333-3333-333333333332"),
                                    Position = 1,
                                    Prompt = "Yo ___ estudiante.",
                                    _correctChoiceIndex = 0
                                },
                                new
                                {
                                    Id = new Guid("44444444-4444-4444-4444-000000000004"),
                                    Choices = "[\"soy\",\"es\",\"eres\"]",
                                    LessonId = new Guid("33333333-3333-3333-3333-333333333332"),
                                    Position = 2,
                                    Prompt = "Ella ___ profesora.",
                                    _correctChoiceIndex = 1
                                },
                                new
                                {
                                    Id = new Guid("44444444-4444-4444-4444-000000000005"),
                                    Choices = "[\"Un cafe, por favor\",\"Adios\",\"Gracias\"]",
                                    LessonId = new Guid("33333333-3333-3333-3333-333333333333"),
                                    Position = 1,
                                    Prompt = "How do you order a coffee?",
                                    _correctChoiceIndex = 0
                                },
                                new
                                {
                                    Id = new Guid("44444444-4444-4444-4444-000000000006"),
                                    Choices = "[\"leche\",\"agua\",\"pan\"]",
                                    LessonId = new Guid("33333333-3333-3333-3333-333333333333"),
                                    Position = 2,
                                    Prompt = "How do you say water?",
                                    _correctChoiceIndex = 1
                                });
                        });

                    b.Navigation("Exercises");
                });
#pragma warning restore 612, 618
        }
    }
}
